

services:
  client:
    build: ./Client
    image: "client"
    container_name: "client"
    ports:
      - "8002:8000"
    environment:
      - STRING_PROCESSING_ENDPOINT_APP=http://server:8080/jobs

    networks:
      - app

  rabbitmq:
    build: ./RabbitMQ
    image: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    networks:
      - app

  worker1:
    build: ./Worker
    image: "worker"
    container_name: "worker1"
    environment:
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672/app.vhost
      - RABBITMQ_WORK_QUEUE=work_queue
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - app


  artifact:
    build:
     context: ./RestServer
     target: artifact
    image: "artifact"
    container_name: "artifact"
    volumes:
      - server-artifact:/ArtifactBuilder/target
    networks:
      - app

  server:
    build:
      context: ./RestServer
      target: server
    image: "rest.server"
    container_name: "server"
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_VIRTUAL-HOST=app.vhost
      - SPRING_RABBITMQ_USERNAME=app
      - SPRING_RABBITMQ_PASSWORD=app
      - SPRING_RABBITMQ_PORT=5672
    volumes:
      - server-artifact:/target
    networks:
      - app

  server2:
    build:
      context: ./RestServer
      target: server
    image: "rest.server"
    container_name: "server2"
    ports:
      - "8081:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_VIRTUAL-HOST=app.vhost
      - SPRING_RABBITMQ_USERNAME=app
      - SPRING_RABBITMQ_PASSWORD=app
      - SPRING_RABBITMQ_PORT=5672
    volumes:
      - server-artifact:/target
    networks:
      - app

volumes:
  server-artifact:

networks:
  app: