

services:
  client:
    build: ./Client
    image: "client"
    container_name: "client"
    ports:
      - "8002:8000"
    environment:
      - STRING_PROCESSING_ENDPOINT_APP=http://nginx:80/api/executions/public
    networks:
      - app

  rabbitmq:
    build: Persistence/Queues/RabbitMQ
    image: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_USER=app
      - RABBITMQ_PASSWORD=app
      - RABBITMQ_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
      - RABBITMQ_VHOST=app.vhost
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app

  postgres-queue:
    image: "library/postgres"
    container_name: "postgres.queue"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=mq_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=message_queue_db
    volumes:
      - ./Persistence/Queues/PostgreSQL:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  core-database:
    image: "library/postgres"
    container_name: "string.core.database"
    ports:
      - "5434:5432"
    volumes:
      - ./Persistence/Core:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST=core-database
      - POSTGRES_USER=stc_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=string_core_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app


  worker-v1:
    build:
      context: ./Worker
      dockerfile: v1.Dockerfile
    image: "worker.v1"
    environment:
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672/app.vhost
      - RABBITMQ_WORK_QUEUE=work_queue
    deploy:
      mode: replicated
      replicas: ${WORKER_V1_REPLICAS_COUNT}
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - app

  worker-v2:
    build:
      context: ./Worker
      dockerfile: v2.Dockerfile
    image: "worker.v2"
    environment:
      - POSTGRES_DATABASE_USER=mq_admin
      - POSTGRES_DATABASE_PASSWORD=admin
      - POSTGRES_DATABASE_HOST=postgres.queue
      - POSTGRES_DATABASE_PORT=5432
      - POSTGRES_DATABASE=message_queue_db
    deploy:
      mode: replicated
      replicas: ${WORKER_V2_REPLICAS_COUNT}
    depends_on:
      postgres-queue:
          condition: service_healthy
    networks:
      - app

  server:
    build:
      context: ./RestServer
      dockerfile: Dockerfile
    image: "rest.server"
    ports:
      - "8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_VIRTUAL-HOST=app.vhost
      - SPRING_RABBITMQ_USERNAME=app
      - SPRING_RABBITMQ_PASSWORD=app
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_DATASOURCE_QUEUE_URL=jdbc:postgresql://postgres.queue:5432/message_queue_db
      - SPRING_DATASOURCE_QUEUE_USERNAME=mq_admin
      - SPRING_DATASOURCE_QUEUE_PASSWORD=admin
      - SPRING_DATASOURCE_CORE_URL=jdbc:postgresql://string.core.database:5432/string_core_db
      - SPRING_DATASOURCE_CORE_USERNAME=stc_admin
      - SPRING_DATASOURCE_CORE_PASSWORD=admin
      - AUTH_JWT_PRIVATE_KEY=bXBTUmdhV2IyZDlOMzUxaE5NVjNJY3IwazRwaW5meHk=
      - AUTH_JWT_VALID_PERIOD=86400000
      - EXECUTION_CALLBACK_URL=http://nginx:80/api/executions/callback
    deploy:
      mode: replicated
      replicas: ${SERVER_REPLICAS_COUNT}
    depends_on:
       core-database:
          condition: service_healthy
    networks:
      - app

  nginx:
    build: ./LoadBalancer
    ports:
      - "80:80"
    image: "nginx"
    container_name: "nginx"
    volumes:
      - ./LoadBalancer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      server:
        condition: service_started
    networks:
      - app

networks:
  app: