

services:
  client:
    build: ./Client
    image: "client"
    container_name: "client"
    ports:
      - "8002:8000"
    environment:
      - STRING_PROCESSING_ENDPOINT_APP=http://nginx:80/jobs

    networks:
      - app

  rabbitmq:
    build: ./RabbitMQ
    image: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_USER=app
      - RABBITMQ_PASSWORD=app
      - RABBITMQ_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
      - RABBITMQ_VHOST=app.vhost
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    networks:
      - app

  worker:
    build: ./Worker
    image: "worker"
    environment:
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672/app.vhost
      - RABBITMQ_WORK_QUEUE=work_queue
    deploy:
      mode: replicated
      replicas: ${WORKER_REPLICAS_COUNT}
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - app

  server:
    build:
      context: ./RestServer
      dockerfile: Dockerfile
    image: "rest.server"
    ports:
      - "8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_VIRTUAL-HOST=app.vhost
      - SPRING_RABBITMQ_USERNAME=app
      - SPRING_RABBITMQ_PASSWORD=app
      - SPRING_RABBITMQ_PORT=5672
    deploy:
      mode: replicated
      replicas: ${SERVER_REPLICAS_COUNT}
    networks:
      - app

  nginx:
    build: ./Nginx
    ports:
      - "80:80"
    image: "nginx"
    container_name: "nginx"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

networks:
  app: